UIDATIMP-294: Field Mapping Profile details: Order PO & POL from MARC Bib (Create/Edit)
folio-org/ui-data-import pull request #1236
Opened 2022-10-25 14:00 UTC by mariia-aloshyna

## Purpose

To record the details of field mappings and defaults required to create one or more Orders and their Order lines from an imported MARC Bibliographic record file

## Approach

- Implement MappingOrderDetails section

## Refs

https://issues.folio.org/browse/UIDATIMP-294

## Screenshots

![image](https://user-images.githubusercontent.com/55138456/197793568-a9cc07b5-7d5e-4bfe-9ccd-423f075c127b.png)
![image](https://user-images.githubusercontent.com/55138456/197793770-f7d1492c-a366-4e24-9052-8705317b8f63.png)
![image](https://user-images.githubusercontent.com/55138456/197793856-96396f31-3829-4f74-b2ae-bd08aec1e686.png)
![image](https://user-images.githubusercontent.com/55138456/197793926-e9bed232-4a8e-4e63-8899-df6248494bc1.png)
![image](https://user-images.githubusercontent.com/55138456/197793976-67179cec-ca57-49c2-8a36-e43f63f49eb3.png)
![image](https://user-images.githubusercontent.com/55138456/197794038-b36ca312-651d-4166-bbb1-571a26ba2098.png)
![image](https://user-images.githubusercontent.com/55138456/197794100-13d0b411-9403-475b-aed1-7626f98940e6.png)

2022-10-26 10:18 UTC, OleksandrHladchenko1 requested changes

2022-10-26 10:18 UTC, OleksandrHladchenko1 commented on src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/EResourcesDetails.js
> +  FieldOrganization
```suggestion
  FieldOrganization,
```

2022-10-26 10:18 UTC, OleksandrHladchenko1 commented on src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/ItemDetails.js
> +            dateFormat="MM-DD-YYYY"
```suggestion
            dateFormat="YYYY-MM-DD"
```
and add `dateFormat` prop for all the datepickers

2022-10-26 10:18 UTC, OleksandrHladchenko1 commented on src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
> +  useIntl
```suggestion
  useIntl,
```

2022-10-26 13:19 UTC, mariia-aloshyna commented
@folio-org/fe-tl-reviewers take a look, please

2022-10-28 11:04 UTC, OleksandrHladchenko1 approved these changes

2022-10-28 12:39 UTC, Dmitriy-Litvinenko approved these changes

2022-10-28 12:41 UTC, mariia-aloshyna commented on src/settings/MappingProfiles/initialDetails/ORDER.js
> +    path: 'order.po.poStatus', // ?
Described in PR description. Will remove this once @KaterynaSenchenko take a look and we decide what to do with fields that are absent in schemas

2022-10-29 11:29 UTC, merged