UIDATIMP-1301: Change imports for ListTemplate component in ui-data-import
folio-org/ui-data-import pull request #1298
Opened 2022-12-16 15:28 UTC by OleksandrHladchenko1

## Purpose

## Approach

## Refs

## Screenshots

2022-12-17 10:36 UTC, OleksandrHladchenko1 commented
Run unit tests and merge this PR, after [this one](https://github.com/folio-org/stripes-data-transfer-components/pull/233) is merged

2022-12-19 19:27 UTC, artem-blazhko reviewed
Could you fix/add lint ignore to newly appeared eslint issues?

2022-12-23 17:54 UTC, mariia-aloshyna commented
> Could you fix/add lint ignore to newly appeared eslint issues?

Hi @artem-blazhko Done

2022-12-23 17:55 UTC, mariia-aloshyna approved these changes

2022-12-28 22:10 UTC, zburke requested changes
Numerous test errors make this impossible to review. Additionally, it appears that this work relies on pending work in SDTC 5.4.0, but the `package.json` file here hasn't been updated from `^5.2.0` to reflect the new minimum version. 

Finally, it appears that BigTest has been deprecated within this repo 🎉 given that `yarn test` does not call `test:e2e`, yet there are changes here to `test/bigtest`. Instead of maintaining that cruft, aren't we better off just removing it?

2023-01-03 19:29 UTC, zburke requested changes
The SDTC version is still incorrect.

2023-01-03 19:29 UTC, zburke commented on package.json
> +    "@folio/stripes-data-transfer-components": "^5.3.0",
[SDTC 5.3.0 was published on 2022-10-21](https://github.com/folio-org/stripes-data-transfer-components/releases/tag/v5.3.0). This PR relies on the export `ACTION_TYPES`, which were [just added last week](https://github.com/folio-org/stripes-data-transfer-components/pull/235). The minimum version here must be 5.4.0.

2023-01-04 14:39 UTC, OleksandrHladchenko1 commented
> The SDTC version is still incorrect.

Created PR for bumping SDTC version https://github.com/folio-org/stripes-data-transfer-components/pull/236
And also created ticket https://issues.folio.org/browse/UIDATIMP-1343 to get rid of BigTest in ui-data-import

2023-01-11 16:49 UTC, mariia-aloshyna commented
Hi @zburke Could you double-check the updates, please?

2023-01-16 10:14 UTC, merged