UIDATIMP-1469 Handle cancelation of running composite job...
folio-org/ui-data-import pull request #1455
Opened 2023-08-18 15:43 UTC by JohnC-80

[UIDATIMP-1469](https://issues.folio.org/browse/UIDATIMP-1469)

This implements the cancellation action that's available on import cards. The layout and strings of the content of the following confirmation modal has been adjusted. For the most part, the existing logic path in the code has been maintained.

![image](https://github.com/folio-org/ui-data-import/assets/20704067/3a212cf1-de05-495e-89ba-28fd68096fca)

2023-08-18 15:49 UTC, mariia-aloshyna commented on translations/ui-data-import/en_US.json
Aren't all other files except `en.json` updated by a bot?

2023-08-18 16:47 UTC, ncovercash requested changes
Get that test coverage up and we should be good to go!

2023-08-18 16:47 UTC, ncovercash commented on src/components/Jobs/components/Job/Job.js
> +import { cancelMultipartJob } from '../../../../utils';
Consolidate/fix these imports, there's multiple impotrs from `utils` and it seems like some are weirdly indented?

2023-08-18 16:47 UTC, ncovercash commented on translations/ui-data-import/en_US.json
Looks like [yes](https://wiki.folio.org/display/I18N/How+to+Translate+FOLIO); I think John made those changes so the updated translations would show in his local build

2023-08-23 09:05 UTC, JohnC-80 commented on translations/ui-data-import/en_US.json
I'm aware that translation files outside of en.json do get overwritten - We also need these translations to show up in our rancher environment pointed at this branch, and the lokalize process only runs against the master branch.

2023-08-23 09:25 UTC, mariia-aloshyna approved these changes

2023-08-24 02:46 UTC, ncovercash approved these changes

2023-08-24 02:46 UTC, ncovercash commented on translations/ui-data-import/en.json
> +  "jobSummarySourceFileLabel": "Source file: ",
Where is this being used?

2023-08-24 04:44 UTC, merged